<?php

return [
    /*
    |--------------------------------------------------------------------------
    | KP Form definitions for blotter
    |--------------------------------------------------------------------------
    | Each form has: id (value in select), label, title, purpose, fields.
    | Field types: resident | resident_multi | text | textarea | date
    | Storage: complainant_id, respondent_id in columns; rest in form_data.
    | Regex for form numbers in docx: /\bKP FORM (Number|No\.?)\s+[0-9A-Za-z-]+/i
    */

    'forms' => [
        [
            'id' => '1',
            'label' => 'KP Form No. 1',
            'title' => 'Selection List',
            'title_en' => 'Selection List',
            'purpose' => 'Select up to 25 residents and/or add manual names. Include a deadline date.',
            'fields' => [
                ['name' => 'member_ids', 'type' => 'resident_multi', 'label' => 'Selected residents (up to 25)', 'required' => false, 'max' => 25],
                ['name' => 'manual_members', 'type' => 'textarea', 'label' => 'Manual names (one per line)', 'required' => false],
                ['name' => 'deadline_date', 'type' => 'date', 'label' => 'Deadline date', 'required' => true],
            ],
        ],
        [
            'id' => '2',
            'label' => 'KP Form No. 2',
            'title' => 'Katuldloan (Appointment)',
            'title_en' => 'Appointment of Lupon member',
            'purpose' => 'Formal appointment of a selected Lupon member; term from oath-taking up to 3 years.',
            'fields' => [
                ['name' => 'appointee_id', 'type' => 'resident', 'label' => 'Appointee', 'required' => true],
                ['name' => 'oath_date', 'type' => 'date', 'label' => 'Oath-taking date', 'required' => true],
                ['name' => 'term_years', 'type' => 'text', 'label' => 'Term (e.g. 3 years)', 'required' => true],
            ],
        ],
        [
            'id' => '3',
            'label' => 'KP Form No. 3',
            'title' => 'Pahibalo sa Katuldloan (Notice of Appointment)',
            'title_en' => 'Notice that someone has been chosen as Lupon member',
            'purpose' => 'Inform the appointee of selection; when and where oath-taking will occur.',
            'fields' => [
                ['name' => 'appointee_id', 'type' => 'resident', 'label' => 'Appointee', 'required' => true],
                ['name' => 'oath_date', 'type' => 'date', 'label' => 'Oath-taking date', 'required' => true],
                ['name' => 'oath_venue', 'type' => 'text', 'label' => 'Oath-taking venue', 'required' => true],
            ],
        ],
        [
            'id' => '4',
            'label' => 'KP Form No. 4',
            'title' => 'Talaan sa mga Gitudlong Sakop sa Lupon',
            'title_en' => 'List of appointed Lupon members',
            'purpose' => 'Final list of all confirmed Lupon members (up to 20); signed by Punong Barangay and Barangay Secretary.',
            'fields' => [
                ['name' => 'member_ids', 'type' => 'resident_multi', 'label' => 'Lupon members (up to 20)', 'required' => true, 'max' => 20],
                ['name' => 'record_date', 'type' => 'date', 'label' => 'Record date', 'required' => true],
            ],
        ],
        [
            'id' => '5',
            'label' => 'KP Form No. 5',
            'title' => 'Panumpa sa Katungdanan (Oath of Office)',
            'title_en' => 'Oath of Office',
            'purpose' => 'Statement sworn by the Lupon member promising to perform duties; signed by member and administered by Punong Barangay.',
            'fields' => [
                ['name' => 'member_id', 'type' => 'resident', 'label' => 'Member', 'required' => true],
                ['name' => 'oath_date', 'type' => 'date', 'label' => 'Oath date', 'required' => true],
            ],
        ],
        [
            'id' => '6',
            'label' => 'KP Form No. 6',
            'title' => 'Pagsibog sa Katuldloan (Removal of Appointment)',
            'title_en' => 'Removal of Appointment',
            'purpose' => 'Used to remove a Lupon member for valid reasons (e.g. incompetence, unworthiness); signed by PB and witnesses.',
            'fields' => [
                ['name' => 'member_id', 'type' => 'resident', 'label' => 'Member to remove', 'required' => true],
                ['name' => 'reason', 'type' => 'textarea', 'label' => 'Reason for removal', 'required' => true],
                ['name' => 'witness_ids', 'type' => 'resident_multi', 'label' => 'Witnesses (up to 12)', 'required' => true, 'max' => 12],
                ['name' => 'incapacity_example_line1', 'type' => 'text', 'label' => 'Incapacity example line 1', 'required' => false],
                ['name' => 'received_date', 'type' => 'date', 'label' => 'Received date', 'required' => false],
            ],
        ],
        [
            'id' => '7',
            'label' => 'KP Form No. 7',
            'title' => 'Reklamo (Complaint)',
            'title_en' => 'Complaint',
            'purpose' => 'Complainant files a barangay case against respondent; states violation and relief requested.',
            'fields' => [
                ['name' => 'complainant_ids', 'type' => 'resident_multi', 'label' => 'Complainant(s) (up to 3)', 'required' => false, 'max' => 3],
                ['name' => 'respondent_ids', 'type' => 'resident_multi', 'label' => 'Respondent(s) (up to 3)', 'required' => false, 'max' => 3],
                ['name' => 'violation', 'type' => 'textarea', 'label' => 'Violation / complaint', 'required' => true],
                ['name' => 'case_description', 'type' => 'textarea', 'label' => 'Case description', 'required' => true],
                ['name' => 'relief_requested', 'type' => 'textarea', 'label' => 'Relief requested', 'required' => true],
                ['name' => 'incident_date', 'type' => 'date', 'label' => 'Incident / filing date', 'required' => true],
                ['name' => 'execution_date', 'type' => 'date', 'label' => 'Execution date', 'required' => false],
            ],
        ],
        [
            'id' => '8',
            'label' => 'KP Form No. 8',
            'title' => 'Pahibalo Bahin sa Bista (Mediation Hearing Notice)',
            'title_en' => 'Mediation Hearing Notice',
            'purpose' => 'Informs the complainant of the schedule for mediation hearing.',
            'fields' => [
                ['name' => 'resident_ids', 'type' => 'resident_multi', 'label' => 'Residents (up to 3)', 'required' => false, 'max' => 3],
                ['name' => 'complainant_id', 'type' => 'resident', 'label' => 'Complainant (fallback)', 'required' => true],
                ['name' => 'hearing_date', 'type' => 'date', 'label' => 'Hearing date', 'required' => true],
                ['name' => 'hearing_venue', 'type' => 'text', 'label' => 'Hearing venue', 'required' => true],
                ['name' => 'case_reference', 'type' => 'text', 'label' => 'Case reference (optional)', 'required' => false],
                ['name' => 'hearing_time', 'type' => 'text', 'label' => 'Hearing time', 'required' => false],
                ['name' => 'delivered_date', 'type' => 'date', 'label' => 'Delivered date', 'required' => false],
                ['name' => 'ack_date', 'type' => 'date', 'label' => 'Acknowledgement date', 'required' => false],
            ],
        ],
        [
            'id' => '9',
            'label' => 'KP Form No. 9 Page 1',
            'title' => 'Mga Pagtawag (Summons)',
            'title_en' => 'Summons',
            'purpose' => 'Summons respondents to appear for confrontation/mediation; with proof of service on page 2.',
            'fields' => [
                ['name' => 'complainant_ids', 'type' => 'resident_multi', 'label' => 'Complainant(s) (up to 3)', 'required' => false, 'max' => 3],
                ['name' => 'respondent_ids', 'type' => 'resident_multi', 'label' => 'Respondent(s) (up to 4)', 'required' => true, 'max' => 4],
                ['name' => 'case_subject', 'type' => 'text', 'label' => 'Case subject', 'required' => true],
                ['name' => 'case_description', 'type' => 'textarea', 'label' => 'Case description', 'required' => true],
                ['name' => 'hearing_date', 'type' => 'date', 'label' => 'Hearing date', 'required' => true],
                ['name' => 'hearing_venue', 'type' => 'text', 'label' => 'Hearing venue', 'required' => true],
                ['name' => 'case_reference', 'type' => 'text', 'label' => 'Case reference (optional)', 'required' => false],
                ['name' => 'hearing_time', 'type' => 'text', 'label' => 'Hearing time', 'required' => false],
                ['name' => 'issued_date', 'type' => 'date', 'label' => 'Issued date', 'required' => false],
            ],
        ],
        [
            'id' => '9-2',
            'label' => 'KP Form No. 9 Page 2',
            'title' => 'Mga Pagtawag (Summons) - Page 2',
            'title_en' => 'Summons - Page 2',
            'purpose' => 'Page 2 of Summons (Officer\'s Return).',
            'fields' => [
                ['name' => 'respondent_id_1', 'type' => 'resident', 'label' => 'Respondent 1', 'required' => true],
                ['name' => 'respondent_id_2', 'type' => 'resident', 'label' => 'Respondent 2', 'required' => false],
                ['name' => 'hearing_date', 'type' => 'date', 'label' => 'Hearing date', 'required' => true],
                ['name' => 'hearing_venue', 'type' => 'text', 'label' => 'Hearing venue', 'required' => true],
                ['name' => 'case_reference', 'type' => 'text', 'label' => 'Case reference (optional)', 'required' => false],
                ['name' => 'summon1_date', 'type' => 'date', 'label' => 'Summon 1 date', 'required' => false],
                ['name' => 'summon2_date', 'type' => 'date', 'label' => 'Summon 2 date', 'required' => false],
                ['name' => 'summon_result_1', 'type' => 'text', 'label' => 'Summon result 1', 'required' => false],
                ['name' => 'summon_result_2', 'type' => 'text', 'label' => 'Summon result 2', 'required' => false],
                ['name' => 'summon_result_3', 'type' => 'text', 'label' => 'Summon result 3', 'required' => false],
                ['name' => 'summon_result_4', 'type' => 'text', 'label' => 'Summon result 4', 'required' => false],
                ['name' => 'recipient_date_1', 'type' => 'date', 'label' => 'Recipient date 1', 'required' => false],
            ],
        ],
        [
            'id' => '9-A',
            'label' => 'KP Form No. 9-A',
            'title' => 'Pagtawag (Summons by Pangkat)',
            'title_en' => 'Summons by Pangkat',
            'purpose' => 'Used when the case has escalated from Punong Barangay to Pangkat; similar to Form 9 but from Pangkat level.',
            'fields' => [
                ['name' => 'complainant_ids', 'type' => 'resident_multi', 'label' => 'Complainant(s) (up to 4)', 'required' => false, 'max' => 4],
                ['name' => 'respondent_ids', 'type' => 'resident_multi', 'label' => 'Respondent(s) (up to 4)', 'required' => true, 'max' => 4],
                ['name' => 'case_subject', 'type' => 'text', 'label' => 'Case subject', 'required' => true],
                ['name' => 'case_description', 'type' => 'textarea', 'label' => 'Case description', 'required' => true],
                ['name' => 'hearing_date', 'type' => 'date', 'label' => 'Hearing date', 'required' => true],
                ['name' => 'hearing_venue', 'type' => 'text', 'label' => 'Hearing venue', 'required' => true],
                ['name' => 'hearing_time', 'type' => 'text', 'label' => 'Hearing time', 'required' => false],
                ['name' => 'case_reference', 'type' => 'text', 'label' => 'Case reference (optional)', 'required' => false],
                ['name' => 'issued_date', 'type' => 'date', 'label' => 'Issued date', 'required' => false],
            ],
        ],
        [
            'id' => '10',
            'label' => 'KP Form No. 10',
            'title' => 'Pahibalo Bahin sa Pagporma sa Pangkat',
            'title_en' => 'Notice to form Pangkat Tagapagkasundo',
            'purpose' => 'Notify parties to form the Pangkat Tagapagkasundo when mediation by PB fails.',
            'fields' => [
                ['name' => 'complainant_ids', 'type' => 'resident_multi', 'label' => 'Complainant(s) (up to 4)', 'required' => false, 'max' => 4],
                ['name' => 'respondent_ids', 'type' => 'resident_multi', 'label' => 'Respondent(s) (up to 4)', 'required' => false, 'max' => 4],
                ['name' => 'formation_date', 'type' => 'date', 'label' => 'Formation date', 'required' => true],
                ['name' => 'formation_time', 'type' => 'text', 'label' => 'Formation time', 'required' => false],
                ['name' => 'hearing_venue', 'type' => 'text', 'label' => 'Venue', 'required' => true],
                ['name' => 'issued_date', 'type' => 'date', 'label' => 'Issued date', 'required' => false],
                ['name' => 'deadline_date', 'type' => 'date', 'label' => 'Deadline date', 'required' => false],
                ['name' => 'case_reference', 'type' => 'text', 'label' => 'Case reference (optional)', 'required' => false],
            ],
        ],
        [
            'id' => '11',
            'label' => 'KP Form No. 11',
            'title' => 'Pahibalo sa Napiling Sakop sa Pangkat',
            'title_en' => 'Notice of selected Pangkat member',
            'purpose' => 'Inform a chosen Pangkat member that he/she was selected.',
            'fields' => [
                ['name' => 'member_id', 'type' => 'resident', 'label' => 'Selected Pangkat member', 'required' => true],
                ['name' => 'case_number', 'type' => 'text', 'label' => 'Case number', 'required' => false],
                ['name' => 'complainant_ids', 'type' => 'resident_multi', 'label' => 'Complainant(s) (up to 3)', 'required' => false, 'max' => 3],
                ['name' => 'respondent_ids', 'type' => 'resident_multi', 'label' => 'Respondent(s) (up to 3)', 'required' => false, 'max' => 3],
                ['name' => 'case_subject', 'type' => 'text', 'label' => 'Case subject', 'required' => false],
                ['name' => 'issued_date', 'type' => 'date', 'label' => 'Issued date', 'required' => false],
                ['name' => 'received_date', 'type' => 'date', 'label' => 'Received date', 'required' => false],
                ['name' => 'selection_date', 'type' => 'date', 'label' => 'Selection date', 'required' => true],
                ['name' => 'case_reference', 'type' => 'text', 'label' => 'Case reference (optional)', 'required' => false],
            ],
        ],
        [
            'id' => '12',
            'label' => 'KP Form No. 12',
            'title' => 'Pahibalo sa Husay (Conciliation Hearing)',
            'title_en' => 'Conciliation Hearing Notice',
            'purpose' => 'Notify both parties of Pangkat conciliation hearing schedule.',
            'fields' => [
                ['name' => 'complainant_ids', 'type' => 'resident_multi', 'label' => 'Complainant(s) (up to 2)', 'required' => false, 'max' => 2],
                ['name' => 'respondent_ids', 'type' => 'resident_multi', 'label' => 'Respondent(s) (up to 2)', 'required' => false, 'max' => 2],
                ['name' => 'hearing_date', 'type' => 'date', 'label' => 'Hearing date', 'required' => true],
                ['name' => 'hearing_venue', 'type' => 'text', 'label' => 'Hearing venue', 'required' => true],
                ['name' => 'conciliation_date', 'type' => 'date', 'label' => 'Conciliation date (optional)', 'required' => false],
                ['name' => 'conciliation_time', 'type' => 'text', 'label' => 'Conciliation time', 'required' => false],
                ['name' => 'issued_date', 'type' => 'date', 'label' => 'Issued date', 'required' => false],
                ['name' => 'served_date', 'type' => 'date', 'label' => 'Served date', 'required' => false],
                ['name' => 'case_reference', 'type' => 'text', 'label' => 'Case reference (optional)', 'required' => false],
            ],
        ],
        [
            'id' => '13',
            'label' => 'KP Form No. 13',
            'title' => 'Subpoena (Testigo)',
            'title_en' => 'Subpoena (Witness)',
            'purpose' => 'Orders witnesses to appear and testify in the hearing.',
            'fields' => [
                ['name' => 'complainant_ids', 'type' => 'resident_multi', 'label' => 'Complainant(s) (up to 3)', 'required' => false, 'max' => 3],
                ['name' => 'respondent_ids', 'type' => 'resident_multi', 'label' => 'Respondent(s) (up to 3)', 'required' => false, 'max' => 3],
                ['name' => 'witness_ids', 'type' => 'resident_multi', 'label' => 'Witness(es) (up to 8)', 'required' => false, 'max' => 8, 'min' => 1],
                ['name' => 'case_description', 'type' => 'textarea', 'label' => 'Case description', 'required' => true],
                ['name' => 'appearance_date', 'type' => 'date', 'label' => 'Appearance date', 'required' => true],
                ['name' => 'appearance_time', 'type' => 'text', 'label' => 'Appearance time', 'required' => true],
                ['name' => 'issued_date', 'type' => 'date', 'label' => 'Issued date', 'required' => false],
                ['name' => 'hearing_venue', 'type' => 'text', 'label' => 'Hearing venue', 'required' => false],
                ['name' => 'case_reference', 'type' => 'text', 'label' => 'Case reference (optional)', 'required' => false],
            ],
        ],
        [
            'id' => '14',
            'label' => 'KP Form No. 14',
            'title' => 'Kasabotan sa Husay (Agreement/Settlement)',
            'title_en' => 'Settlement Agreement',
            'purpose' => 'Used when both parties voluntarily settle and agree to terms; signed by both and certified by PB.',
            'fields' => [
                ['name' => 'complainant_ids', 'type' => 'resident_multi', 'label' => 'Complainant(s) (up to 2) (max 2)', 'required' => false, 'max' => 2],
                ['name' => 'respondent_ids', 'type' => 'resident_multi', 'label' => 'Respondent(s) (up to 2) (max 2)', 'required' => false, 'max' => 2],
                ['name' => 'case_subject', 'type' => 'text', 'label' => 'Case number', 'required' => false],
                ['name' => 'case_description', 'type' => 'textarea', 'label' => 'Case description', 'required' => false],
                ['name' => 'agreement_terms', 'type' => 'textarea', 'label' => 'Agreement / settlement terms', 'required' => true],
                ['name' => 'settlement_date', 'type' => 'date', 'label' => 'Settlement date', 'required' => true],
            ],
        ],
        [
            'id' => '15',
            'label' => 'KP Form No. 15',
            'title' => 'Ganti sa Husay (Award/Decision)',
            'title_en' => 'Award / Decision',
            'purpose' => 'Decision issued by PB or Pangkat when no settlement occurs; contains the final ruling.',
            'fields' => [
                ['name' => 'complainant_ids', 'type' => 'resident_multi', 'label' => 'Complainant(s) (up to 3)', 'required' => false, 'max' => 3],
                ['name' => 'respondent_ids', 'type' => 'resident_multi', 'label' => 'Respondent(s) (up to 3)', 'required' => false, 'max' => 3],
                ['name' => 'case_subject', 'type' => 'text', 'label' => 'Case number', 'required' => false],
                ['name' => 'case_description', 'type' => 'textarea', 'label' => 'Case description', 'required' => false],
                ['name' => 'conciliation_award_details', 'type' => 'textarea', 'label' => 'Conciliation award details', 'required' => true],
                ['name' => 'decision_date', 'type' => 'date', 'label' => 'Decision date', 'required' => true],
            ],
        ],
        [
            'id' => '16',
            'label' => 'KP Form No. 16',
            'title' => 'Amicable Settlement',
            'title_en' => 'Amicable Settlement',
            'purpose' => 'Both complainant and respondent agree to settle. They list the settlement terms and sign. Settlement terms written; signed voluntarily; certified by Lupon/Pangkat chairman.',
            'fields' => [
                ['name' => 'complainant_ids', 'type' => 'resident_multi', 'label' => 'Complainant(s) (up to 3)', 'required' => false, 'max' => 3],
                ['name' => 'respondent_ids', 'type' => 'resident_multi', 'label' => 'Respondent(s) (up to 3)', 'required' => false, 'max' => 3],
                ['name' => 'case_subject', 'type' => 'text', 'label' => 'Case number', 'required' => false],
                ['name' => 'case_description', 'type' => 'textarea', 'label' => 'Case description', 'required' => false],
                ['name' => 'amicable_settlement_details', 'type' => 'textarea', 'label' => 'Amicable settlement details', 'required' => true],
                ['name' => 'delivery_date', 'type' => 'date', 'label' => 'Delivery date', 'required' => true],
            ],
        ],
        [
            'id' => '17',
            'label' => 'KP Form No. 17',
            'title' => 'Rejection of Settlement',
            'title_en' => 'Rejection of Settlement',
            'purpose' => 'A party rejects the settlement due to fraud (Limbong), intimidation (Panghasi), or threat (Hulga). Includes signed statement, reason for rejection, sworn before Punong Barangay.',
            'fields' => [
                ['name' => 'complainant_ids', 'type' => 'resident_multi', 'label' => 'Complainant(s) (up to 2)', 'required' => false, 'max' => 2],
                ['name' => 'respondent_ids', 'type' => 'resident_multi', 'label' => 'Respondent(s) (up to 2)', 'required' => false, 'max' => 2],
                ['name' => 'case_subject', 'type' => 'text', 'label' => 'Case number', 'required' => false],
                ['name' => 'case_description', 'type' => 'textarea', 'label' => 'Case description', 'required' => false],
                ['name' => 'reason_fraud', 'type' => 'textarea', 'label' => 'Reason: Fraud (Limbong)', 'required' => false],
                ['name' => 'reason_coercion', 'type' => 'textarea', 'label' => 'Reason: Coercion (Panghasi)', 'required' => false],
                ['name' => 'reason_threat', 'type' => 'textarea', 'label' => 'Reason: Threat (Hulga)', 'required' => false],
                ['name' => 'sworn_place', 'type' => 'text', 'label' => 'Sworn place (Lugar)', 'required' => false],
                ['name' => 'sworn_date', 'type' => 'date', 'label' => 'Sworn date', 'required' => false],
                ['name' => 'received_date', 'type' => 'date', 'label' => 'Received date', 'required' => false],
                ['name' => 'case_reference', 'type' => 'text', 'label' => 'Case reference (optional)', 'required' => false],
            ],
        ],
        [
            'id' => '18',
            'label' => 'KP Form No. 18',
            'title' => 'Notice of Hearing (Failure to Appear – Complainant)',
            'title_en' => 'Notice of Hearing – Complainant Failure to Appear',
            'purpose' => 'Sent to complainant(s) who failed to appear. Requires explanation why they didn\'t attend; warns about possible dismissal or certification barring court action.',
            'fields' => [
                ['name' => 'complainant_ids', 'type' => 'resident_multi', 'label' => 'Complainant(s) (up to 3)', 'required' => false, 'max' => 3],
                ['name' => 'respondent_ids', 'type' => 'resident_multi', 'label' => 'Respondent(s) (up to 3)', 'required' => false, 'max' => 3],
                ['name' => 'case_subject', 'type' => 'text', 'label' => 'Case number', 'required' => false],
                ['name' => 'case_description', 'type' => 'textarea', 'label' => 'Case description', 'required' => false],
                ['name' => 'hearing_date', 'type' => 'date', 'label' => 'Hearing date', 'required' => true],
                ['name' => 'hearing_time', 'type' => 'text', 'label' => 'Hearing time', 'required' => false],
                ['name' => 'issued_date', 'type' => 'date', 'label' => 'Issued date', 'required' => false],
                ['name' => 'original_appointment_date', 'type' => 'date', 'label' => 'Original appointment date', 'required' => false],
                ['name' => 'delivered_date', 'type' => 'date', 'label' => 'Delivered date', 'required' => false],
                ['name' => 'hearing_venue', 'type' => 'text', 'label' => 'Hearing venue', 'required' => false],
            ],
        ],
        [
            'id' => '19',
            'label' => 'KP Form No. 19',
            'title' => 'Notice of Hearing (Failure to Appear – Respondent)',
            'title_en' => 'Notice of Hearing – Respondent Failure to Appear',
            'purpose' => 'Sent to respondent(s) who failed to appear. Requires explanation for absence; warns about consequences such as counterclaim dismissal.',
            'fields' => [
                ['name' => 'complainant_ids', 'type' => 'resident_multi', 'label' => 'Complainant(s) (up to 3)', 'required' => false, 'max' => 3],
                ['name' => 'respondent_ids', 'type' => 'resident_multi', 'label' => 'Respondent(s) (up to 3)', 'required' => false, 'max' => 3],
                ['name' => 'case_subject', 'type' => 'text', 'label' => 'Case number', 'required' => false],
                ['name' => 'case_description', 'type' => 'textarea', 'label' => 'Case description', 'required' => false],
                ['name' => 'hearing_date', 'type' => 'date', 'label' => 'Hearing date', 'required' => true],
                ['name' => 'hearing_time', 'type' => 'text', 'label' => 'Hearing time', 'required' => false],
                ['name' => 'issued_date', 'type' => 'date', 'label' => 'Issued date', 'required' => false],
                ['name' => 'original_appointment_date', 'type' => 'date', 'label' => 'Original appointment date', 'required' => false],
                ['name' => 'delivered_date', 'type' => 'date', 'label' => 'Delivered date', 'required' => false],
                ['name' => 'hearing_venue', 'type' => 'text', 'label' => 'Hearing venue', 'required' => false],
                ['name' => 'case_reference', 'type' => 'text', 'label' => 'Case reference (optional)', 'required' => false],
            ],
        ],
        [
            'id' => '20',
            'label' => 'KP Form No. 20',
            'title' => 'Certification to File Action (After Settlement Rejected)',
            'title_en' => 'Certification to File Action – Settlement Rejected',
            'purpose' => 'Issued when personal confrontation happened, there was a settlement but later rejected under oath. Parties can now file in court.',
            'fields' => [
                ['name' => 'complainant_ids', 'type' => 'resident_multi', 'label' => 'Complainant(s) (up to 3)', 'required' => false, 'max' => 3],
                ['name' => 'respondent_ids', 'type' => 'resident_multi', 'label' => 'Respondent(s) (up to 3)', 'required' => false, 'max' => 3],
                ['name' => 'case_subject', 'type' => 'text', 'label' => 'Case number', 'required' => false],
                ['name' => 'case_description', 'type' => 'textarea', 'label' => 'Case description', 'required' => false],
                ['name' => 'official_name', 'type' => 'text', 'label' => 'Punong Barangay name (official)', 'required' => false],
                ['name' => 'certification_date', 'type' => 'date', 'label' => 'Certification date', 'required' => true],
                ['name' => 'confrontation_date', 'type' => 'date', 'label' => 'Date of personal confrontation', 'required' => true],
                ['name' => 'settlement_rejected_date', 'type' => 'date', 'label' => 'Settlement rejected under oath (date)', 'required' => false],
                ['name' => 'case_reference', 'type' => 'text', 'label' => 'Case reference (optional)', 'required' => false],
            ],
        ],
        [
            'id' => '20-A',
            'label' => 'KP Form No. 20-A',
            'title' => 'Certification to File Action (After Failure of Conciliation)',
            'title_en' => 'Certification to File Action – Failure of Conciliation',
            'purpose' => 'Issued when mediation failed, Pangkat formed, conciliation failed. Case can now be filed in court.',
            'fields' => [
                ['name' => 'complainant_ids', 'type' => 'resident_multi', 'label' => 'Complainant(s) (up to 3)', 'required' => false, 'max' => 3],
                ['name' => 'respondent_ids', 'type' => 'resident_multi', 'label' => 'Respondent(s) (up to 3)', 'required' => false, 'max' => 3],
                ['name' => 'case_subject', 'type' => 'text', 'label' => 'Case subject', 'required' => false],
                ['name' => 'case_description', 'type' => 'textarea', 'label' => 'Case description', 'required' => false],
                ['name' => 'certification_date', 'type' => 'date', 'label' => 'Certification date', 'required' => true],
                ['name' => 'mediation_failed_date', 'type' => 'date', 'label' => 'Mediation failed (date)', 'required' => false],
                ['name' => 'conciliation_failed_date', 'type' => 'date', 'label' => 'Conciliation failed (date)', 'required' => false],
                ['name' => 'case_reference', 'type' => 'text', 'label' => 'Case reference (optional)', 'required' => false],
            ],
        ],
        [
            'id' => '20-B',
            'label' => 'KP Form No. 20-B',
            'title' => 'Certification to File Action (Respondent Failed to Appear)',
            'title_en' => 'Certification to File Action – Respondent Failed to Appear',
            'purpose' => 'Issued when respondent intentionally did not attend despite notice. Case may now go to court.',
            'fields' => [
                ['name' => 'complainant_ids', 'type' => 'resident_multi', 'label' => 'Complainant(s) (up to 3)', 'required' => false, 'max' => 3],
                ['name' => 'respondent_ids', 'type' => 'resident_multi', 'label' => 'Respondent(s) (up to 3)', 'required' => false, 'max' => 3],
                ['name' => 'case_subject', 'type' => 'text', 'label' => 'Case subject', 'required' => false],
                ['name' => 'case_description', 'type' => 'textarea', 'label' => 'Case description', 'required' => false],
                ['name' => 'certification_date', 'type' => 'date', 'label' => 'Certification date', 'required' => true],
                ['name' => 'respondent_failed_date', 'type' => 'date', 'label' => 'Respondent failed to appear (date)', 'required' => false],
                ['name' => 'case_reference', 'type' => 'text', 'label' => 'Case reference (optional)', 'required' => false],
            ],
        ],
        [
            'id' => '20-B-a',
            'label' => 'KP Form No. 20-B-a',
            'title' => 'Certification to File Action (Failure at Punong + Failure at Pangkat)',
            'title_en' => 'Certification to File Action – Failure at PB and Pangkat',
            'purpose' => 'Issued when failed settlement at Punong Barangay, Pangkat meeting set, respondent still failed or refused to appear.',
            'fields' => [
                ['name' => 'complainant_ids', 'type' => 'resident_multi', 'label' => 'Complainant(s) (up to 3)', 'required' => false, 'max' => 3],
                ['name' => 'respondent_ids', 'type' => 'resident_multi', 'label' => 'Respondent(s) (up to 3)', 'required' => false, 'max' => 3],
                ['name' => 'case_subject', 'type' => 'text', 'label' => 'Case subject', 'required' => false],
                ['name' => 'case_description', 'type' => 'textarea', 'label' => 'Case description', 'required' => false],
                ['name' => 'certification_date', 'type' => 'date', 'label' => 'Certification date', 'required' => true],
                ['name' => 'failure_at_punong_date', 'type' => 'date', 'label' => 'Failure at Punong Barangay (date)', 'required' => false],
                ['name' => 'pangkat_meeting_date', 'type' => 'date', 'label' => 'Pangkat meeting set (date)', 'required' => false],
                ['name' => 'respondent_failed_pangkat_date', 'type' => 'date', 'label' => 'Respondent failed at Pangkat (date)', 'required' => false],
                ['name' => 'case_reference', 'type' => 'text', 'label' => 'Case reference (optional)', 'required' => false],
            ],
        ],
        [
            'id' => '21',
            'label' => 'KP Form No. 21',
            'title' => 'Certification to Bar Action',
            'title_en' => 'Certification to Bar Action',
            'purpose' => 'Issued when complainant refused or failed to appear. Case is dismissed; complainant is barred from filing in court.',
            'fields' => [
                ['name' => 'complainant_ids', 'type' => 'resident_multi', 'label' => 'Complainant(s) (up to 2)', 'required' => false, 'max' => 2],
                ['name' => 'respondent_ids', 'type' => 'resident_multi', 'label' => 'Respondent(s) (up to 2)', 'required' => false, 'max' => 2],
                ['name' => 'case_subject', 'type' => 'text', 'label' => 'Case subject', 'required' => false],
                ['name' => 'case_description', 'type' => 'textarea', 'label' => 'Case description', 'required' => false],
                ['name' => 'basis_for_bar', 'type' => 'text', 'label' => 'Basis for bar (order reference)', 'required' => false],
                ['name' => 'certification_date', 'type' => 'date', 'label' => 'Certification date', 'required' => true],
                ['name' => 'complainant_failed_date', 'type' => 'date', 'label' => 'Complainant failed to appear (date)', 'required' => false],
                ['name' => 'case_reference', 'type' => 'text', 'label' => 'Case reference (optional)', 'required' => false],
            ],
        ],
        [
            'id' => '22',
            'label' => 'KP Form No. 22',
            'title' => 'Certification to Bar Counterclaim',
            'title_en' => 'Certification to Bar Counterclaim',
            'purpose' => 'Issued when respondent failed or refused to appear without valid reason. Bars respondent from filing counterclaim related to the complaint.',
            'fields' => [
                ['name' => 'complainant_ids', 'type' => 'resident_multi', 'label' => 'Complainant(s) (up to 3)', 'required' => false, 'max' => 3],
                ['name' => 'respondent_ids', 'type' => 'resident_multi', 'label' => 'Respondent(s) (up to 3)', 'required' => false, 'max' => 3],
                ['name' => 'case_subject', 'type' => 'text', 'label' => 'Case number', 'required' => false],
                ['name' => 'case_description', 'type' => 'textarea', 'label' => 'Case description', 'required' => false],
                ['name' => 'certification_date', 'type' => 'date', 'label' => 'Certification date', 'required' => true],
                ['name' => 'case_reference', 'type' => 'text', 'label' => 'Case reference (optional)', 'required' => false],
            ],
        ],
        [
            'id' => '23',
            'label' => 'KP Form No. 23',
            'title' => 'Motion for Execution',
            'title_en' => 'Motion for Execution',
            'purpose' => 'Used by parties to request execution of settlement or arbitration award, after 10 days with no rejection.',
            'fields' => [
                ['name' => 'complainant_ids', 'type' => 'resident_multi', 'label' => 'Complainant(s) (up to 3)', 'required' => false, 'max' => 3],
                ['name' => 'respondent_ids', 'type' => 'resident_multi', 'label' => 'Respondent(s) (up to 3)', 'required' => false, 'max' => 3],
                ['name' => 'case_subject', 'type' => 'text', 'label' => 'Case number', 'required' => false],
                ['name' => 'case_description', 'type' => 'textarea', 'label' => 'Case description', 'required' => false],
                ['name' => 'arbitration_date', 'type' => 'date', 'label' => 'Arbitration award/decision date', 'required' => true],
                ['name' => 'writ_type', 'type' => 'text', 'label' => 'Writ type', 'required' => false],
                ['name' => 'date_issued', 'type' => 'date', 'label' => 'Date issued', 'required' => true],
                ['name' => 'case_reference', 'type' => 'text', 'label' => 'Case reference (optional)', 'required' => false],
            ],
        ],
        [
            'id' => '24',
            'label' => 'KP Form No. 24',
            'title' => 'Notice of Hearing (Motion for Execution)',
            'title_en' => 'Notice of Hearing – Motion for Execution',
            'purpose' => 'Sent to both parties to notify that there will be a hearing for execution.',
            'fields' => [
                ['name' => 'complainant_ids', 'type' => 'resident_multi', 'label' => 'Complainant(s) (up to 3)', 'required' => false, 'max' => 3],
                ['name' => 'respondent_ids', 'type' => 'resident_multi', 'label' => 'Respondent(s) (up to 3)', 'required' => false, 'max' => 3],
                ['name' => 'case_subject', 'type' => 'text', 'label' => 'Case number', 'required' => false],
                ['name' => 'case_description', 'type' => 'textarea', 'label' => 'Case description', 'required' => false],
                ['name' => 'hearing_date', 'type' => 'date', 'label' => 'Hearing date', 'required' => true],
                ['name' => 'hearing_time', 'type' => 'text', 'label' => 'Hearing time', 'required' => false],
                ['name' => 'hearing_venue', 'type' => 'text', 'label' => 'Hearing venue', 'required' => false],
                ['name' => 'filing_party', 'type' => 'text', 'label' => 'Filing party', 'required' => false],
                ['name' => 'issued_date', 'type' => 'date', 'label' => 'Issued date', 'required' => true],
                ['name' => 'delivered_date', 'type' => 'date', 'label' => 'Delivered date', 'required' => false],
                ['name' => 'case_reference', 'type' => 'text', 'label' => 'Case reference (optional)', 'required' => false],
            ],
        ],
        [
            'id' => '25',
            'label' => 'KP Form No. 25',
            'title' => 'Notice of Execution',
            'title_en' => 'Notice of Execution',
            'purpose' => 'Issued when settlement/agreement exists and respondent failed to comply. Allows execution against personal property.',
            'fields' => [
                ['name' => 'complainant_ids', 'type' => 'resident_multi', 'label' => 'Complainant(s) (up to 2)', 'required' => false, 'max' => 2],
                ['name' => 'respondent_ids', 'type' => 'resident_multi', 'label' => 'Respondent(s) (up to 2)', 'required' => false, 'max' => 2],
                ['name' => 'case_subject', 'type' => 'text', 'label' => 'Case number', 'required' => false],
                ['name' => 'case_description', 'type' => 'textarea', 'label' => 'Case description', 'required' => false],
                ['name' => 'agreement_date', 'type' => 'date', 'label' => 'Agreement date', 'required' => true],
                ['name' => 'award_terms', 'type' => 'textarea', 'label' => 'Award/settlement terms', 'required' => true],
                ['name' => 'amount', 'type' => 'text', 'label' => 'Amount', 'required' => false],
                ['name' => 'issued_date', 'type' => 'date', 'label' => 'Issued date', 'required' => true],
                ['name' => 'case_reference', 'type' => 'text', 'label' => 'Case reference (optional)', 'required' => false],
            ],
        ],
        [
            'id' => 'dismissal-order',
            'label' => 'Improvised KP Form – Dismissal Order',
            'title' => 'Dismissal Order',
            'title_en' => 'Dismissal Order',
            'purpose' => 'Used when complainant fails to appear without valid reason. Case is dismissed.',
            'fields' => [
                ['name' => 'complainant_ids', 'type' => 'resident_multi', 'label' => 'Complainant(s) (up to 2)', 'required' => false, 'max' => 2],
                ['name' => 'respondent_ids', 'type' => 'resident_multi', 'label' => 'Respondent(s) (up to 3)', 'required' => false, 'max' => 3],
                ['name' => 'case_subject', 'type' => 'text', 'label' => 'Case number', 'required' => false],
                ['name' => 'case_description', 'type' => 'textarea', 'label' => 'Case description', 'required' => false],
                ['name' => 'issued_date', 'type' => 'date', 'label' => 'Issued date', 'required' => true],
            ],
        ],
        [
            'id' => 'minutes-of-proceedings',
            'label' => 'Minutes of Proceedings Document',
            'title' => 'Minutes of Proceedings',
            'title_en' => 'Minutes of Proceedings',
            'purpose' => 'Summary of mediation/conciliation; signatures of parties; certification by secretary.',
            'fields' => [
                ['name' => 'complainant_ids', 'type' => 'resident_multi', 'label' => 'Complainant(s) (up to 3)', 'required' => false, 'max' => 3],
                ['name' => 'respondent_ids', 'type' => 'resident_multi', 'label' => 'Respondent(s) (up to 3)', 'required' => false, 'max' => 3],
                ['name' => 'case_subject', 'type' => 'text', 'label' => 'Case number', 'required' => false],
                ['name' => 'case_description', 'type' => 'text', 'label' => 'Case description', 'required' => false],
                ['name' => 'mediator_name', 'type' => 'text', 'label' => 'Mediator name', 'required' => false],
                ['name' => 'date', 'type' => 'date', 'label' => 'Date', 'required' => true],
                ['name' => 'time', 'type' => 'text', 'label' => 'Time', 'required' => true],
                ['name' => 'mediation_summary', 'type' => 'textarea', 'label' => 'Summary of mediation/conciliation', 'required' => true],
            ],
        ],
        [
            'id' => 'case-record',
            'label' => 'Case Record Form (Nature of Case / Outcome)',
            'title' => 'Case Record – Nature of Case / Outcome',
            'title_en' => 'Case Record',
            'purpose' => 'Case details; nature (Civil/Criminal/etc.); dates of mediation/conciliation; outcome (Settled / Not Settled); settlement summary if any.',
            'fields' => [
                ['name' => 'complainant_ids', 'type' => 'resident_multi', 'label' => 'Complainant(s) (up to 2)', 'required' => false, 'max' => 2],
                ['name' => 'respondent_ids', 'type' => 'resident_multi', 'label' => 'Respondent(s) (up to 2)', 'required' => false, 'max' => 2],
                ['name' => 'case_subject', 'type' => 'text', 'label' => 'Brgy. Case No.', 'required' => false],
                ['name' => 'case_description', 'type' => 'text', 'label' => 'For (case description)', 'required' => false],
                ['name' => 'date_filed', 'type' => 'date', 'label' => 'Date filed', 'required' => false],
                ['name' => 'date_served', 'type' => 'date', 'label' => 'Date served', 'required' => false],
                ['name' => 'summons_served_by', 'type' => 'text', 'label' => 'Summons served by', 'required' => false],
                ['name' => 'summons_served_to', 'type' => 'text', 'label' => 'Summons served to', 'required' => false],
                ['name' => 'mediation_dates', 'type' => 'textarea', 'label' => 'Dates of mediation', 'required' => false],
                ['name' => 'conciliation_dates', 'type' => 'textarea', 'label' => 'Dates of conciliation', 'required' => false],
                ['name' => 'mediator_name', 'type' => 'text', 'label' => 'Mediator name', 'required' => false],
                ['name' => 'conciliator_name', 'type' => 'text', 'label' => 'Conciliator name', 'required' => false],
                ['name' => 'chairman_name', 'type' => 'text', 'label' => 'Chairman name', 'required' => false],
                ['name' => 'secretary_name', 'type' => 'text', 'label' => 'Secretary name', 'required' => false],
                ['name' => 'member_name', 'type' => 'text', 'label' => 'Member name', 'required' => false],
                ['name' => 'gist_of_settlement', 'type' => 'textarea', 'label' => 'Gist of settlement', 'required' => false],
                ['name' => 'remarks', 'type' => 'textarea', 'label' => 'Remarks', 'required' => false],
            ],
        ],
    ],

    /*
    | Regex to match form numbers in the single KP DOCX template.
    | Handles: KP Form Number 1, KP Form No. 9-A, KP Form No. 20-B-a, etc.
    */
    'form_number_regex' => '/\bKP FORM (Number|No\.?)\s+[0-9A-Za-z-]+/i',

    /*
    | Single KP form DOCX template (34 pages). Each page contains a different form.
    | Pages are identified by "KP Form No. X" headings. Export extracts the matching
    | page for the selected form and fills placeholders.
    */
    'docx_template' => resource_path('views/certificates/templates/kp_form.docx'),
    'blotter_docs_disk' => 'public',
    'blotter_docs_path' => 'blotter_docs',
];
