DROP DATABASE IF EXISTS `profiling-system`;
CREATE DATABASE `profiling-system`;
USE `profiling-system`;
CREATE TABLE `residents` (
  `id` int(11) NOT NULL,
  `first_name` varchar(100) NOT NULL,
  `middle_name` varchar(100) DEFAULT NULL,
  `surname` varchar(100) NOT NULL,
  `suffix` varchar(10) DEFAULT NULL,
  `birthdate` date NOT NULL,
  `birthplace` varchar(150) DEFAULT NULL,
  `age` int(11) DEFAULT NULL,
  `sex` varchar(20) NOT NULL DEFAULT 'Male',
  `lgbtq_identity` varchar(100) DEFAULT NULL,
  `lgbtq_other_text` varchar(200) DEFAULT NULL,
  `civil_status` enum('Single','Married','Widowed','Divorced') DEFAULT NULL,
  `nationality` varchar(50) DEFAULT 'Filipino',
  `religion` varchar(100) DEFAULT NULL,
  `ethnicity` varchar(100) DEFAULT NULL,
  `blood_type` varchar(10) DEFAULT NULL,
  `height` decimal(5,2) DEFAULT NULL,
  `weight` decimal(5,2) DEFAULT NULL,
  `father_name` varchar(200) DEFAULT NULL,
  `father_occupation` varchar(200) DEFAULT NULL,
  `mother_name` varchar(200) DEFAULT NULL,
  `mother_occupation` varchar(200) DEFAULT NULL,
  `philhealth_no` varchar(30) DEFAULT NULL,
  `length_of_residency` int(11) DEFAULT NULL,
  `house_ownership` varchar(30) DEFAULT NULL,
  `house_material` varchar(50) DEFAULT NULL,
  `toilet_type` varchar(30) DEFAULT NULL,
  `water_source` varchar(50) DEFAULT NULL,
  `is_4ps` varchar(3) DEFAULT 'No',
  `is_nhts` varchar(3) DEFAULT 'No',
  `is_solo_parent` varchar(3) DEFAULT 'No',
  `is_smoker` varchar(3) DEFAULT 'No',
  `is_binge_drinker` varchar(3) DEFAULT 'No',
  `has_hypertension` varchar(3) DEFAULT 'No',
  `has_diabetes` varchar(3) DEFAULT 'No',
  `has_asthma` varchar(3) DEFAULT 'No',
  `has_tb` varchar(3) DEFAULT 'No',
  `has_cancer` varchar(3) DEFAULT 'No',
  `has_mental_health` varchar(3) DEFAULT 'No',
  `membership_type` varchar(30) DEFAULT NULL,
  `family_planning` varchar(3) DEFAULT 'No',
  `is_pwd` enum('Yes','No') DEFAULT 'No',
  `pwd_type` varchar(200) DEFAULT NULL,
  `pwd_id_no` varchar(50) DEFAULT NULL,
  `is_deceased` enum('Yes','No') DEFAULT 'No',
  `date_of_death` date DEFAULT NULL,
  `is_newborn` enum('Yes','No') DEFAULT 'No',
  `purok` varchar(50) DEFAULT NULL,
  `household_no` varchar(20) DEFAULT NULL,
  `barangay` varchar(100) NOT NULL DEFAULT 'Santo Rosario',
  `municipality` varchar(100) DEFAULT NULL,
  `province` varchar(100) DEFAULT NULL,
  `household_position` varchar(50) DEFAULT NULL,
  `total_household` int(11) DEFAULT NULL,
  `voters_status` enum('Yes','No') DEFAULT 'No',
  `educational_attainment` enum('None','Elementary','High School','Senior High','College','Vocational','Post Graduate') DEFAULT NULL,
  `grade_level` varchar(50) DEFAULT NULL,
  `school_name` varchar(150) DEFAULT NULL,
  `course` varchar(150) DEFAULT NULL,
  `course_other` varchar(150) DEFAULT NULL,
  `graduation_date` date DEFAULT NULL,
  `eligibility` varchar(100) DEFAULT NULL,
  `eligibility_other` varchar(150) DEFAULT NULL,
  `contact_no` varchar(20) DEFAULT NULL,
  `email` varchar(150) DEFAULT NULL,
  `occupation_type` varchar(100) DEFAULT NULL,
  `occupation` varchar(100) DEFAULT NULL,
  `monthly_income` decimal(15,2) DEFAULT NULL,
  `annual_income` decimal(15,2) DEFAULT NULL,
  `socioeconomic_status` varchar(50) DEFAULT NULL,
  `image_path` varchar(255) NOT NULL,
  `is_deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` datetime DEFAULT NULL,
  `is_purok_president` tinyint(1) NOT NULL DEFAULT 0,
  `id_front_image` varchar(255) DEFAULT NULL,
  `id_back_image` varchar(255) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `username` varchar(50) DEFAULT NULL,
  `password` varchar(255) DEFAULT NULL,
  `account_status` enum('active','inactive','suspended') DEFAULT 'active',
  `user_role` enum('resident','admin','staff') DEFAULT 'resident',
  `last_login` datetime DEFAULT NULL,
  `login_attempts` int(3) NOT NULL DEFAULT 0,
  `lockout_until` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
SHOW WARNINGS;
SHOW ERRORS;
