<?php
require_once '../config/config.php';
require_once '../includes/functions.php';
requireAdmin();

// Check if IDs are provided
if ($_SERVER['REQUEST_METHOD'] !== 'POST' || empty($_POST['feedback_ids'])) {
    echo "<script>alert('No feedback selected.'); window.close();</script>";
    exit();
}

$feedback_ids = $_POST['feedback_ids'];
$ids_placeholder = implode(',', array_fill(0, count($feedback_ids), '?'));

// Fetch feedback details
$sql = "SELECT f.*, u.username, u.email, c.name as category_name 
        FROM feedback f 
        JOIN `profiling-system`.residents u ON f.user_id = u.id 
        JOIN categories c ON f.category_id = c.id 
        WHERE f.id IN ($ids_placeholder)
        ORDER BY f.created_at DESC";

$stmt = $conn->prepare($sql);
$types = str_repeat('i', count($feedback_ids));
$stmt->bind_param($types, ...$feedback_ids);
$stmt->execute();
$result = $stmt->get_result();
$feedback_items = [];
while ($row = $result->fetch_assoc()) {
    $feedback_items[] = $row;
}

// Stats for the report
$total_items = count($feedback_items);
$positive = 0;
$negative = 0;
$neutral = 0;
foreach ($feedback_items as $item) {
    if ($item['sentiment'] == 'Positive') $positive++;
    elseif ($item['sentiment'] == 'Negative') $negative++;
    else $neutral++;
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Feedback Report - <?php echo date('Y-m-d'); ?></title>
    <link rel="icon" href="../img/logo.png" type="image/png">
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #1F3A93;
            padding-bottom: 15px;
        }
        .header h1 {
            margin: 0;
            color: #1a317d;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        .report-info {
            display: flex;
            justify-content: space-between;
            margin-bottom: 20px;
            background: #f9fafb;
            padding: 15px;
            border-radius: 8px;
            border: 1px solid #e5e7eb;
        }
        .stats-summary {
            display: flex;
            gap: 20px;
        }
        .stat-box {
            background: white;
            padding: 5px 15px;
            border-radius: 15px;
            border: 1px solid #ddd;
            font-size: 14px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            font-size: 12px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
            vertical-align: top;
        }
        th {
            background-color: #f0f7ff;
            color: #1a317d;
        }
        tr:nth-child(even) {
            background-color: #f9fafb;
        }
        .badge {
            display: inline-block;
            padding: 2px 6px;
            border-radius: 12px;
            font-size: 10px;
            font-weight: bold;
        }
        .bg-positive { background: #e0f2fe; color: #1a317d; }
        .bg-negative { background: #fee2e2; color: #991b1b; }
        .bg-neutral { background: #fef3c7; color: #92400e; }
        
        @media print {
            .no-print { display: none; }
            body { padding: 0; }
            table { width: 100%; }
        }
    </style>
</head>
<body onload="window.print()">
    <div class="header">
        <h1>Feedback Report</h1>
        <p>Barangay Sto. Rosario Feedback System</p>
    </div>

    <div class="report-info">
        <div>
            <strong>Date Generated:</strong> <?php echo date('F j, Y, g:i a'); ?><br>
            <strong>Generated By:</strong> <?php echo htmlspecialchars($_SESSION['username']); ?><br>
            <strong>Total Records:</strong> <?php echo $total_items; ?>
        </div>
        <div class="stats-summary">
            <div class="stat-box">Positive: <strong><?php echo $positive; ?></strong></div>
            <div class="stat-box">Negative: <strong><?php echo $negative; ?></strong></div>
            <div class="stat-box">Neutral: <strong><?php echo $neutral; ?></strong></div>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th width="3%">#</th>
                <th width="12%">Date</th>
                <th width="15%">User / Email</th>
                <th width="10%">Category</th>
                <th width="8%">Rating</th>
                <th width="30%">Comment</th>
                <th width="10%">Sentiment</th>
                <th width="12%">Status</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($feedback_items as $index => $item): ?>
                <tr>
                    <td><?php echo $index + 1; ?></td>
                    <td><?php echo date('M d, Y', strtotime($item['created_at'])); ?></td>
                    <td>
                        <strong><?php echo htmlspecialchars($item['username']); ?></strong><br>
                        <span style="color: #666; font-size: 10px;"><?php echo htmlspecialchars($item['email']); ?></span>
                    </td>
                    <td><?php echo htmlspecialchars($item['category_name']); ?></td>
                    <td><?php echo $item['rating']; ?> / 5</td>
                    <td><?php echo nl2br(htmlspecialchars($item['comment'])); ?></td>
                    <td>
                        <?php 
                        $badgeClass = '';
                        if ($item['sentiment'] == 'Positive') $badgeClass = 'bg-positive';
                        elseif ($item['sentiment'] == 'Negative') $badgeClass = 'bg-negative';
                        else $badgeClass = 'bg-neutral';
                        ?>
                        <span class="badge <?php echo $badgeClass; ?>"><?php echo $item['sentiment']; ?></span>
                    </td>
                    <td>
                        <?php if ($item['is_resolved']): ?>
                            <span style="color:green; font-weight:bold;">Resolved</span><br>
                            <span style="font-size:9px; color:#555;">By: <?php echo htmlspecialchars($item['resolved_by']); ?></span>
                        <?php else: ?>
                            <span style="color:red;">Pending</span>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <div class="no-print" style="margin-top: 20px; text-align: center;">
        <button onclick="window.print()" style="padding: 10px 20px; background: #1F3A93; color: white; border: none; border-radius: 5px; cursor: pointer;">Print Report</button>
        <button onclick="window.close()" style="padding: 10px 20px; background: #6b7280; color: white; border: none; border-radius: 5px; cursor: pointer; margin-left: 10px;">Close Window</button>
    </div>
</body>
</html>
